#!/bin/ash

#
# App : AutoDisconnect
# Url : https://garage.maemo.org/projects/autodisconnect/
# Version: 0.4
# Author: Aymeric Brisse <aymeric.brisse@gmail.com>
# License: GNU General Public License
#

AUTODISCONNECT=/opt/autodisconnect/autodisconnect-pre-network-check

if [ ! -x $AUTODISCONNECT ]; then
	exit 0
fi

$AUTODISCONNECT
